### ISSUE TITLE
pip install -e . - does not seem to work

### ISSUE THREAD

**Issue by henrikstranneheim** [dnil/rhocall#3]
pip install -e .
Obtaining file:///mnt/hds/proj/cust003/develop/modules/rhocall
  Running setup.py egg_info for package from file:///mnt/hds/proj/cust003/develop/modules/rhocall

Downloading/unpacking numpy (from rhocall==0.1)
  Downloading numpy-1.11.2.tar.gz (4.2MB): 4.2MB downloaded
  Running setup.py egg_info for package numpy
    Running from numpy source directory.

    warning: no previously-included files matching '*.pyc' found anywhere in distribution
    warning: no previously-included files matching '*.pyo' found anywhere in distribution
    warning: no previously-included files matching '*.pyd' found anywhere in distribution
Downloading/unpacking cyvcf2==0.6.2 (from rhocall==0.1)
  Downloading cyvcf2-0.6.2.tar.gz (964kB): 964kB downloaded
  Running setup.py egg_info for package cyvcf2
    Traceback (most recent call last):
      File "<string>", line 16, in <module>
      File "/tmp/pip_build_henrik.stranneheim/cyvcf2/setup.py", line 3, in <module>
        import numpy as np
    ImportError: No module named numpy
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):

  File "<string>", line 16, in <module>

  File "/tmp/pip_build_henrik.stranneheim/cyvcf2/setup.py", line 3, in <module>

    import numpy as np

ImportError: No module named numpy

----------------------------------------
Cleaning up..

**Comment by dnil** [comment]
Thanks; something is loose on the reading-the-requirements.txt.. Lets see what we can do.
In the meantime, works if all reqs are installed: 
```
conda create -n rhocall_test2 python=3.5
source activate rhocall_test2
pip install numpy
pip install Cython
pip install -r requirements.txt
pip install -e .
```

**Comment by dnil** [comment]
..and on the topic of requirements and references, note that the recommended mode of use includes requiring bcftools with a local population reference vcf, e.g. swegen - or 1000g.

**Comment by moonso** [comment]
Let's just skip cyvcf2:)

**Comment by dnil** [comment]
Mmm... The install process *seems* fixed again in 0.6.5, but then there is some weird issue with paths for their interface instead.

**Comment by dnil** [comment]
Marking this solved with update of readme, but agree on the deps side. Eventually..

**Comment by henrikstranneheim** [comment]
pip install -e .
Obtaining file:///mnt/hds/proj/cust003/modules/rhocall
  Running setup.py egg_info for package from file:///mnt/hds/proj/cust003/modules/rhocall

Requirement already satisfied (use --upgrade to upgrade): numpy in /mnt/hds/proj/cust003/develop/modules/miniconda2/envs/mip4.0/lib/python2.7/site-packages (from rhocall==0.1)
Requirement already satisfied (use --upgrade to upgrade): Cython in /mnt/hds/proj/cust003/develop/modules/miniconda2/envs/mip4.0/lib/python2.7/site-packages (from rhocall==0.1)
Requirement already satisfied (use --upgrade to upgrade): cyvcf2==0.6.2 in /mnt/hds/proj/cust003/develop/modules/miniconda2/envs/mip4.0/lib/python2.7/site-packages (from rhocall==0.1)
Requirement already satisfied (use --upgrade to upgrade): click in /mnt/hds/proj/cust003/develop/modules/miniconda2/envs/mip4.0/lib/python2.7/site-packages (from rhocall==0.1)
Installing collected packages: rhocall
  Running setup.py develop for rhocall

    Creating /mnt/hds/proj/cust003/develop/modules/miniconda2/envs/mip4.0/lib/python2.7/site-packages/rhocall.egg-link (link to .)
    rhocall 0.1 is already the active version in easy-install.pth
    Installing rhocall script to /mnt/hds/proj/cust003/develop/modules/miniconda2/envs/mip4.0/bin

    Installed /mnt/hds/proj/cust003/modules/rhocall
Successfully installed rhocall
Cleaning up...
(mip4.0)[henrik.stranneheim@rastapopoulos rhocall]$ rhocall
Traceback (most recent call last):
  File "/mnt/hds/proj/cust003/develop/modules/miniconda2/envs/mip4.0/bin/rhocall", line 11, in <module>
    load_entry_point('rhocall', 'console_scripts', 'rhocall')()
  File "/mnt/hds/proj/cust003/develop/modules/miniconda2/envs/mip4.0/lib/python2.7/site-packages/setuptools-27.2.0-py2.7.egg/pkg_resources/__init__.py", line 565, in load_entry_point
  File "/mnt/hds/proj/cust003/develop/modules/miniconda2/envs/mip4.0/lib/python2.7/site-packages/setuptools-27.2.0-py2.7.egg/pkg_resources/__init__.py", line 2598, in load_entry_point
  File "/mnt/hds/proj/cust003/develop/modules/miniconda2/envs/mip4.0/lib/python2.7/site-packages/setuptools-27.2.0-py2.7.egg/pkg_resources/__init__.py", line 2258, in load
  File "/mnt/hds/proj/cust003/develop/modules/miniconda2/envs/mip4.0/lib/python2.7/site-packages/setuptools-27.2.0-py2.7.egg/pkg_resources/__init__.py", line 2264, in resolve
  File "/mnt/hds/proj/cust003/modules/rhocall/rhocall/__main__.py", line 3, in <module>
    from rhocall.cli import cli
  File "/mnt/hds/proj/cust003/modules/rhocall/rhocall/cli.py", line 10, in <module>
    from .run_aggregate import run_aggregate
ImportError: No module named run_aggregate

**Comment by dnil** [comment]
Do you absolutely want to run python2? ;-) Only tested with python=3.5; I can give it a go with 2.7 if you would be helped by it?

**Comment by henrikstranneheim** [comment]
That would be great! there are some other python 2.7 deps in the production conda env and it seems cumbersome to have to create another one just for rohcall. 

But is this import error related to the python version?

**Comment by dnil** [comment]
:-) Only indirectly.. Just learning about the magic of pip caching. Added the module, confirmed working on a naive system with 3.5. Apparently operational also on 2.7, but haven't really tested through everything there yet..
